name: Generate static 'Euler Project' files
description: Generates all the static files for the 'Euler Project' directory

runs:
  using: "composite"  
  steps:
    - name: Genereate LaTeX PDFs
      run: ./makelatex.sh
      working-directory: euler
      shell: bash
    - name: Commit LaTeX PDFs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add ./**/*.pdf
        if [-z "$(git status --porcelain)"]; then
        echo "::set-output name=push::false"
        else 
        echo "::set-output name=push::true"
        fi
        #- name: Push Euler LaTeX
        #  if: steps.commit.latex-commit.outputs.push == 'true'
        #  uses: ad-m/github-push-action@master
        #  with:
        #    github-token: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
    - name: Generate Problem Pages
      run: ./makepages.sh
      working-directory: euler
      shell: bash
