name: Generate static 'Euler Project' files
description: Generates all the static files for the 'Euler Project' directory

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs: 
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      pdf: ${{ steps.filter.outputs.pdf }}
      js: ${{ steps.filter.outputs.js }}
      c: ${{ steps.filter.outputs.c }}
      asm: ${{ steps.filter.outputs.asm }}
      any: ${{ steps.filter.outputs.anything }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            pdf: 
              - 'euler/**/*.tex'
            js: 
              - 'euler/**/*.js'
            c: 
              - 'euler/**/*.c'
            asm:
              - 'euler/**/*.asm'
            anything: 
              - 'euler/**/'

  euler:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.anything }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Generate LaTeX PDFs
      if: ${{ needs.check-changes.outputs.pdf }}
      run: ./makelatex.sh
      working-directory: euler
      shell: bash
    - name: Commit Euler Files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add .
        if [[ -n "$(git status --porcelain)" ]]; then
        git commit -m "Generate Euler Files" -m "[skip actions]"
        echo "PUSH_EULER=true" >> $GITHUB_ENV
        else 
        echo "PUSH_EULER=false" >> $GITHUB_ENV
        fi
      shell: bash
    - name: Push Euler Files
      if: env.PUSH_EULER == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate Problem Pages
      run: ./makepages.sh
      working-directory: euler
      shell: bash
    - name: Upload Euler Artifact
      uses: actions/upload-artifact@v4
      with:
        name: euler-pages
        path: euler
        github-token: ${{ secrets.GITHUB_TOKEN }}
